api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: false
      targetPort: 80
      transport: http
      allowInsecure: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
  template:
    containers:
      - image: {{ .Image }}
        name: healthchecks
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: HealthChecksUI__EvaluationTimeInSeconds
            value: "30"
          - name: HealthChecksUI__HealthChecks__0__Name
            value: Web API
          - name: HealthChecksUI__HealthChecks__0__Uri
            value: http://webapi/health
          - name: HealthChecksUI__HealthChecks__1__Name
            value: Admin Portal
          - name: HealthChecksUI__HealthChecks__1__Uri
            value: http://admin/health
          - name: HealthChecksUI__MinimumSecondsBetweenFailureNotifications
            value: "60"
    scale:
      minReplicas: 1
tags:
  azd-service-name: healthchecks
  aspire-resource-name: healthchecks
