api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: false
      targetPort: {{ targetPortOrDefault 8080 }}
      transport: http
      allowInsecure: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: connectionstrings--blobstorage
        value: '{{ .Env.STORAGE_BLOBENDPOINT }}'
      - name: connectionstrings--defaultconnection
        value: Host=postgres;Port=5432;Username=postgres;Password={{ securedParameter "postgres_password" }};Database=numbatwallet
      - name: connectionstrings--redis
        value: redis:6379,password={{ securedParameter "redis_password" }}
      - name: connectionstrings--blobs
        value: '{{ .Env.STORAGE_BLOBENDPOINT }}'
      - name: connectionstrings--numbatwallet
        value: Host=postgres;Port=5432;Username=postgres;Password={{ securedParameter "postgres_password" }};Database=numbatwallet
      - name: connectionstrings--redis
        value: redis:6379,password={{ securedParameter "redis_password" }}
  template:
    containers:
      - image: {{ .Image }}
        name: webapi
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: HTTP_PORTS
            value: '{{ targetPortOrDefault 0 }}'
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: ConnectionStrings__BlobStorage
            secretRef: connectionstrings--blobstorage
          - name: ConnectionStrings__DefaultConnection
            secretRef: connectionstrings--defaultconnection
          - name: ConnectionStrings__Redis
            secretRef: connectionstrings--redis
          - name: ConnectionStrings__blobs
            secretRef: connectionstrings--blobs
          - name: ConnectionStrings__numbatwallet
            secretRef: connectionstrings--numbatwallet
          - name: ConnectionStrings__redis
            secretRef: connectionstrings--redis
    scale:
      minReplicas: 1
tags:
  azd-service-name: webapi
  aspire-resource-name: webapi
