// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NumbatWallet.Infrastructure.Data;

#nullable disable

namespace NumbatWallet.Infrastructure.Migrations
{
    [DbContext(typeof(NumbatWalletDbContext))]
    [Migration("20260612132531_AddPresentationRequests")]
    partial class AddPresentationRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NumbatWallet.Domain.Aggregates.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<string>("CredentialData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("credential_data");

                    b.Property<string>("CredentialId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("credential_id");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("credential_type");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("IssuerId")
                        .HasColumnType("uuid")
                        .HasColumnName("issuer_id");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("modified_by");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SchemaId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("schema_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("suspension_reason");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id")
                        .HasName("pk_credentials");

                    b.HasIndex("IssuerId")
                        .HasDatabaseName("ix_credentials_issuer_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_credentials_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_credentials_tenant_id");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("ix_credentials_wallet_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_credentials_tenant_id_status");

                    b.HasIndex("TenantId", "WalletId")
                        .HasDatabaseName("ix_credentials_tenant_id_wallet_id");

                    b.HasIndex("WalletId", "Status")
                        .HasDatabaseName("ix_credentials_wallet_id_status");

                    b.ToTable("Credentials", (string)null);
                });

            modelBuilder.Entity("NumbatWallet.Domain.Aggregates.Issuer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CertificateExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("certificate_expires_at");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<string>("DeactivationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("deactivation_reason");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsTrusted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_trusted");

                    b.Property<string>("IssuerDid")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("issuer_did");

                    b.Property<string>("Jurisdiction")
                        .HasColumnType("text")
                        .HasColumnName("jurisdiction");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("public_key");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TrustLevel")
                        .HasColumnType("integer")
                        .HasColumnName("trust_level");

                    b.Property<string>("TrustedDomain")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("trusted_domain");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("pk_issuers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_issuers_code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_issuers_is_active");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_issuers_tenant_id");

                    b.HasIndex("TrustedDomain")
                        .IsUnique()
                        .HasDatabaseName("ix_issuers_trusted_domain");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("ix_issuers_tenant_id_is_active");

                    b.ToTable("Issuers", (string)null);
                });

            modelBuilder.Entity("NumbatWallet.Domain.Aggregates.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_organizations_name");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_organizations_tenant_id");

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("NumbatWallet.Domain.Aggregates.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("EmailSearchToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("email_search_token");

                    b.Property<int>("EmailVerificationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("email_verification_status");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<int>("FailedPinAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_pin_attempts");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("last_name");

                    b.Property<DateTimeOffset?>("LastPinAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_pin_attempt_at");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("text")
                        .HasColumnName("mobile_number");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("modified_by");

                    b.Property<string>("PhoneSearchToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("phone_search_token");

                    b.Property<int>("PhoneVerificationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("phone_verification_status");

                    b.Property<string>("PinHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pin_hash");

                    b.Property<DateTimeOffset?>("PinLockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pin_locked_until");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("VerificationLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("verification_level");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("pk_persons");

                    b.HasIndex("EmailSearchToken")
                        .HasDatabaseName("ix_persons_email_search_token");

                    b.HasIndex("PhoneSearchToken")
                        .HasDatabaseName("ix_persons_phone_search_token");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_persons_tenant_id");

                    b.ToTable("Persons", (string)null);
                });

            modelBuilder.Entity("NumbatWallet.Domain.Aggregates.Presentation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<string>("DisclosedClaimsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("disclosed_claims_json");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("modified_by");

                    b.Property<DateTimeOffset>("PresentedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("presented_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("purpose");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<int>("VerificationCount")
                        .HasColumnType("integer")
                        .HasColumnName("verification_count");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<string>("VerifierId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("verifier_id");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id")
                        .HasName("pk_presentations");

                    b.HasIndex("CredentialId")
                        .HasDatabaseName("ix_presentations_credential_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_presentations_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_presentations_tenant_id");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("ix_presentations_wallet_id");

                    b.HasIndex("TenantId", "WalletId")
                        .HasDatabaseName("ix_presentations_tenant_id_wallet_id");

                    b.ToTable("Presentations", (string)null);
                });

            modelBuilder.Entity("NumbatWallet.Domain.Aggregates.PresentationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("FulfilledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fulfilled_at");

                    b.Property<Guid?>("FulfilledByPresentationId")
                        .HasColumnType("uuid")
                        .HasColumnName("fulfilled_by_presentation_id");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("nonce");

                    b.Property<string>("PresentationDefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("presentation_definition_json");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("purpose");

                    b.Property<string>("RequestedClaimsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("requested_claims_json");

                    b.Property<string>("RequestedCredentialType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("requested_credential_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("VerifierId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("verifier_id");

                    b.HasKey("Id")
                        .HasName("pk_presentation_requests");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_presentation_requests_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_presentation_requests_tenant_id");

                    b.HasIndex("TenantId", "VerifierId")
                        .HasDatabaseName("ix_presentation_requests_tenant_id_verifier_id");

                    b.ToTable("PresentationRequests", (string)null);
                });

            modelBuilder.Entity("NumbatWallet.Domain.Aggregates.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_id");

                    b.Property<string>("LockReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("lock_reason");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid?>("PersonId1")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id1");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("suspension_reason");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("WalletDid")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("wallet_did");

                    b.Property<string>("WalletName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("wallet_name");

                    b.HasKey("Id")
                        .HasName("pk_wallets");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_wallets_person_id");

                    b.HasIndex("PersonId1")
                        .HasDatabaseName("ix_wallets_person_id1");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_wallets_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_wallets_tenant_id");

                    b.HasIndex("WalletDid")
                        .IsUnique()
                        .HasDatabaseName("ix_wallets_wallet_did");

                    b.HasIndex("TenantId", "PersonId")
                        .HasDatabaseName("ix_wallets_tenant_id_person_id");

                    b.ToTable("Wallets", (string)null);
                });

            modelBuilder.Entity("NumbatWallet.Domain.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LastPasswordChangeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_password_change_at");

                    b.Property<string>("LockReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("lock_reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.PrimitiveCollection<string>("_roles")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("roles");

                    b.HasKey("Id")
                        .HasName("pk_admin_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_users_email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_admin_users_is_active");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_admin_users_tenant_id");

                    b.HasIndex("LastName", "FirstName")
                        .HasDatabaseName("ix_admin_users_last_name_first_name");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("NumbatWallet.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_type");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("MaxClassification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("max_classification");

                    b.Property<string>("NewValues")
                        .HasColumnType("text")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("text")
                        .HasColumnName("old_values");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_logs_created_at");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_id");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("ix_audit_logs_entity_type");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_audit_logs_tenant_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_type_entity_id");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_tenant_id_created_at");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("NumbatWallet.Domain.Entities.CertificateAuthority", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CertificateData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("certificate_data");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CrlUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("crl_url");

                    b.Property<bool>("IsTrusted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_trusted");

                    b.Property<DateTimeOffset?>("LastValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_validated_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("OcspUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ocsp_url");

                    b.Property<string>("SubjectDn")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("subject_dn");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("thumbprint");

                    b.Property<string>("TrustLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("trust_level");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_certificate_authorities");

                    b.HasIndex("IsTrusted")
                        .HasDatabaseName("ix_certificate_authorities_is_trusted");

                    b.HasIndex("Thumbprint")
                        .IsUnique()
                        .HasDatabaseName("ix_certificate_authorities_thumbprint");

                    b.HasIndex("ValidTo")
                        .HasDatabaseName("ix_certificate_authorities_valid_to");

                    b.ToTable("CertificateAuthorities", (string)null);
                });

            modelBuilder.Entity("NumbatWallet.Domain.Entities.CertificateRevocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("InvalidityDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invalidity_date");

                    b.Property<bool>("IsHold")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hold");

                    b.Property<int>("Reason")
                        .HasColumnType("integer")
                        .HasColumnName("reason");

                    b.Property<DateTime>("RevocationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revocation_date");

                    b.Property<string>("RevokedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("revoked_by");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Thumbprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("thumbprint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_certificate_revocations");

                    b.HasIndex("IsHold")
                        .HasDatabaseName("ix_certificate_revocations_is_hold");

                    b.HasIndex("RevocationDate")
                        .HasDatabaseName("ix_certificate_revocations_revocation_date");

                    b.HasIndex("SerialNumber")
                        .HasDatabaseName("ix_certificate_revocations_serial_number");

                    b.HasIndex("Thumbprint")
                        .HasDatabaseName("ix_certificate_revocations_thumbprint");

                    b.ToTable("CertificateRevocations", (string)null);
                });

            modelBuilder.Entity("NumbatWallet.Domain.Entities.CertificateTrustStore", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("_revokedThumbprints")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("RevokedThumbprints");

                    b.Property<string>("_trustedAuthorityIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("TrustedAuthorityIds");

                    b.Property<string>("_trustedCertificateIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("TrustedCertificateIds");

                    b.HasKey("Id")
                        .HasName("pk_certificate_trust_stores");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_certificate_trust_stores_tenant_id");

                    b.ToTable("CertificateTrustStores", (string)null);
                });

            modelBuilder.Entity("NumbatWallet.Domain.Entities.CredentialSchema", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("SchemaId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("schema_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.Property<string>("_attributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Attributes");

                    b.Property<string>("_contexts")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Contexts");

                    b.Property<string>("_metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Metadata");

                    b.HasKey("Id")
                        .HasName("pk_credential_schemas");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_credential_schemas_is_active");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_credential_schemas_name");

                    b.HasIndex("SchemaId")
                        .IsUnique()
                        .HasDatabaseName("ix_credential_schemas_schema_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_credential_schemas_tenant_id");

                    b.ToTable("CredentialSchemas", (string)null);
                });

            modelBuilder.Entity("NumbatWallet.Domain.Entities.Issuance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("approved_by");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CompletedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("completed_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("credential_type");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<string>("RejectedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rejected_by");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("requester_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.Property<string>("_claims")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("claims");

                    b.Property<string>("_metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.HasKey("Id")
                        .HasName("pk_issuances");

                    b.HasIndex("CredentialType")
                        .HasDatabaseName("ix_issuances_credential_type");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_issuances_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_issuances_tenant_id");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("ix_issuances_wallet_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_issuances_tenant_id_status");

                    b.HasIndex("TenantId", "WalletId")
                        .HasDatabaseName("ix_issuances_tenant_id_wallet_id");

                    b.ToTable("issuances", (string)null);
                });

            modelBuilder.Entity("NumbatWallet.Domain.Entities.RevocationRegistry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("credential_type");

                    b.Property<int>("CurrentCredentials")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_credentials");

                    b.Property<DateTimeOffset?>("FullAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("full_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("IssuerId")
                        .HasColumnType("uuid")
                        .HasColumnName("issuer_id");

                    b.Property<int>("MaxCredentials")
                        .HasColumnType("integer")
                        .HasColumnName("max_credentials");

                    b.Property<string>("RegistryId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("registry_id");

                    b.HasKey("Id")
                        .HasName("pk_revocation_registries");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_revocation_registries_is_active");

                    b.HasIndex("IssuerId")
                        .HasDatabaseName("ix_revocation_registries_issuer_id");

                    b.HasIndex("RegistryId")
                        .IsUnique()
                        .HasDatabaseName("ix_revocation_registries_registry_id");

                    b.HasIndex("IssuerId", "CredentialType")
                        .HasDatabaseName("ix_revocation_registries_issuer_id_credential_type");

                    b.ToTable("RevocationRegistries", (string)null);
                });

            modelBuilder.Entity("NumbatWallet.Domain.Entities.SupportedCredentialType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("IssuerId")
                        .HasColumnType("uuid")
                        .HasColumnName("issuer_id");

                    b.Property<string>("SchemaId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("schema_id");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("schema_version");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("type_name");

                    b.HasKey("Id")
                        .HasName("pk_supported_credential_types");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_supported_credential_types_is_active");

                    b.HasIndex("IssuerId")
                        .HasDatabaseName("ix_supported_credential_types_issuer_id");

                    b.HasIndex("TypeName")
                        .HasDatabaseName("ix_supported_credential_types_type_name");

                    b.HasIndex("IssuerId", "TypeName")
                        .HasDatabaseName("ix_supported_credential_types_issuer_id_type_name");

                    b.ToTable("SupportedCredentialTypes", (string)null);
                });

            modelBuilder.Entity("NumbatWallet.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<string>("SubscriptionTier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subscription_tier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_identifier");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("NumbatWallet.Domain.Entities.TenantCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CertificateData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("certificate_data");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_blocked");

                    b.Property<string>("IssuerDn")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("issuer_dn");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<DateTimeOffset>("NotAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_after");

                    b.Property<DateTimeOffset>("NotBefore")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_before");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("purpose");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("serial_number");

                    b.Property<string>("SubjectDn")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("subject_dn");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("thumbprint");

                    b.Property<string>("TrustLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("trust_level");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("usage_count");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_tenant_certificates");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_tenant_certificates_is_active");

                    b.HasIndex("SerialNumber")
                        .HasDatabaseName("ix_tenant_certificates_serial_number");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_certificates_tenant_id");

                    b.HasIndex("Thumbprint")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_certificates_thumbprint");

                    b.HasIndex("ValidTo")
                        .HasDatabaseName("ix_tenant_certificates_valid_to");

                    b.ToTable("TenantCertificates", (string)null);
                });

            modelBuilder.Entity("NumbatWallet.Domain.Entities.UnmaskAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("approval_reference");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("classification");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("field_name");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UnmaskedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unmasked_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_unmask_audits");

                    b.HasIndex("Classification")
                        .HasDatabaseName("IX_UnmaskAudits_Classification");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_UnmaskAudits_TenantId");

                    b.HasIndex("UnmaskedAt")
                        .HasDatabaseName("IX_UnmaskAudits_UnmaskedAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UnmaskAudits_UserId");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_UnmaskAudits_Entity");

                    b.HasIndex("TenantId", "UnmaskedAt")
                        .HasDatabaseName("IX_UnmaskAudits_TenantId_UnmaskedAt");

                    b.HasIndex("UserId", "UnmaskedAt")
                        .HasDatabaseName("IX_UnmaskAudits_UserId_UnmaskedAt");

                    b.ToTable("unmask_audits", (string)null);
                });

            modelBuilder.Entity("NumbatWallet.Domain.Entities.WalletTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SupportedCredentialTypes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("supported_credential_types");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_wallet_templates");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_wallet_templates_is_active");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_wallet_templates_tenant_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_wallet_templates_type");

                    b.HasIndex("TenantId", "Type")
                        .HasDatabaseName("ix_wallet_templates_tenant_id_type");

                    b.ToTable("WalletTemplates", (string)null);
                });

            modelBuilder.Entity("NumbatWallet.Infrastructure.EventSourcing.EventSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("aggregate_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("SnapshotData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("snapshot_data");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_event_snapshots");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_event_snapshots_tenant_id");

                    b.HasIndex("AggregateId", "Version")
                        .HasDatabaseName("ix_event_snapshots_aggregate_id_version");

                    b.ToTable("EventSnapshots", (string)null);
                });

            modelBuilder.Entity("NumbatWallet.Infrastructure.EventSourcing.StoredEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("aggregate_type");

                    b.Property<string>("CausationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("causation_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_data");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("event_type");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_event_store");

                    b.HasIndex("AggregateId")
                        .HasDatabaseName("ix_event_store_aggregate_id");

                    b.HasIndex("AggregateType")
                        .HasDatabaseName("ix_event_store_aggregate_type");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_event_store_occurred_at");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_event_store_tenant_id");

                    b.HasIndex("AggregateId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_event_store_aggregate_id_version");

                    b.ToTable("EventStore", (string)null);
                });

            modelBuilder.Entity("NumbatWallet.Domain.Aggregates.Credential", b =>
                {
                    b.HasOne("NumbatWallet.Domain.Aggregates.Issuer", "Issuer")
                        .WithMany()
                        .HasForeignKey("IssuerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_credentials_issuers_issuer_id");

                    b.HasOne("NumbatWallet.Domain.Aggregates.Wallet", "Wallet")
                        .WithMany("Credentials")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credentials_wallets_wallet_id");

                    b.Navigation("Issuer");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("NumbatWallet.Domain.Aggregates.Person", b =>
                {
                    b.OwnsOne("NumbatWallet.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("Email");

                            b1.HasKey("PersonId");

                            b1.ToTable("Persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId")
                                .HasConstraintName("fk_persons_persons_id");
                        });

                    b.OwnsOne("NumbatWallet.Domain.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("CountryCode")
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasColumnName("PhoneNumberCountryCode");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("PhoneNumberValue");

                            b1.HasKey("PersonId");

                            b1.ToTable("Persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId")
                                .HasConstraintName("fk_persons_persons_id");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("NumbatWallet.Domain.Aggregates.Presentation", b =>
                {
                    b.HasOne("NumbatWallet.Domain.Aggregates.Credential", null)
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_presentations_credentials_credential_id");
                });

            modelBuilder.Entity("NumbatWallet.Domain.Aggregates.Wallet", b =>
                {
                    b.HasOne("NumbatWallet.Domain.Aggregates.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_wallets_persons_person_id");

                    b.HasOne("NumbatWallet.Domain.Aggregates.Person", null)
                        .WithMany("Wallets")
                        .HasForeignKey("PersonId1")
                        .HasConstraintName("fk_wallets_persons_person_id1");
                });

            modelBuilder.Entity("NumbatWallet.Domain.Entities.RevocationRegistry", b =>
                {
                    b.HasOne("NumbatWallet.Domain.Aggregates.Issuer", null)
                        .WithMany("RevocationRegistries")
                        .HasForeignKey("IssuerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_revocation_registries_issuers_issuer_id");
                });

            modelBuilder.Entity("NumbatWallet.Domain.Entities.SupportedCredentialType", b =>
                {
                    b.HasOne("NumbatWallet.Domain.Aggregates.Issuer", null)
                        .WithMany("SupportedCredentialTypes")
                        .HasForeignKey("IssuerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supported_credential_types_issuers_issuer_id");
                });

            modelBuilder.Entity("NumbatWallet.Domain.Entities.WalletTemplate", b =>
                {
                    b.OwnsMany("NumbatWallet.Domain.Entities.WalletField", "Fields", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("DefaultValue")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("default_value");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("integer")
                                .HasColumnName("display_order");

                            b1.Property<string>("FieldType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("field_type");

                            b1.Property<bool>("IsEditable")
                                .HasColumnType("boolean")
                                .HasColumnName("is_editable");

                            b1.Property<bool>("IsRequired")
                                .HasColumnType("boolean")
                                .HasColumnName("is_required");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("label");

                            b1.Property<string>("MappedCredentialField")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("mapped_credential_field");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.Property<string>("Properties")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("properties");

                            b1.Property<string>("ValidationRule")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("validation_rule");

                            b1.Property<Guid>("WalletTemplateId")
                                .HasColumnType("uuid")
                                .HasColumnName("wallet_template_id");

                            b1.HasKey("Id")
                                .HasName("pk_wallet_template_fields");

                            b1.HasIndex("WalletTemplateId")
                                .HasDatabaseName("ix_wallet_template_fields_wallet_template_id");

                            b1.ToTable("WalletTemplateFields", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WalletTemplateId")
                                .HasConstraintName("fk_wallet_template_fields_wallet_templates_wallet_template_id");
                        });

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("NumbatWallet.Domain.Aggregates.Issuer", b =>
                {
                    b.Navigation("RevocationRegistries");

                    b.Navigation("SupportedCredentialTypes");
                });

            modelBuilder.Entity("NumbatWallet.Domain.Aggregates.Person", b =>
                {
                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("NumbatWallet.Domain.Aggregates.Wallet", b =>
                {
                    b.Navigation("Credentials");
                });
#pragma warning restore 612, 618
        }
    }
}
